### ISSUE TITLE
Feature request: Background color

### ISSUE THREAD

**Issue by Calorion** [hungsu/typomagical-obsidian#33]
I would like to be able to specify a background color for the body field.

**Comment by hungsu** [comment]
Hi @Calorion ! Thankfully this is easy. Do you mind updating your version of Typomagical, and trying the setting in **Typomagical Color Settings** ?

**Comment by hungsu** [comment]
Hi @Calorion ,

Regarding transparent system panes and colour applying to system panes, what version of Obsidian and what operating system did you see this problem on? And by chance are you using the _Translucent window_ setting in _Appearance_ ? I'm not observing this problem on my Windows or Mac machines, on 0.13.26

As for system color picker, that's out of my hands as it's controlled by the Style Settings Plugin. There is discussion about a better picker over here: https://github.com/mgmeyers/obsidian-style-settings/issues/50

**Comment by Smitty010** [comment]
I observed the problem on Windows (Obsidian 1.1.16).  The settings dialog became unreadable as soon as I clicked on "Allow Background color override" (it was the only setting I changed in the Style Settings).  I had to find the typomagical settings in the Style plugin data.json and delete the line to get my Obsidian usable again.

**Comment by hungsu** [comment]
This should be fixed now in Typomagical 1.5.2

**Comment by Calorion** [comment]
Okay! That takes care of 1. Thanks! 

But I’m still having the remaining issues: 

1. The color applies to the Preferences window, the Ribbon, and various other interface elements. I want it to only apply to the main text field.
2. I like using a yellowish (#F7F1E4) color (stolen from iBooks) for my text background. That looks terrible in Dark mode, largely because, in dark mode, the text is grey. I’m not sure of the best solution to this, but perhaps different colors for light and dark modes?

Maybe what I’m actually asking for is a Sepia Theme variant.
